### ISSUE TITLE
BTS custom inference

### ISSUE THREAD

**Issue by mshaheryarmalik** [zhyever/Monocular-Depth-Estimation-Toolbox#27] opened 2022-06-21 16:55 UTC
Hi, I have written custom test file to make prediction on sample dataset without ground truth  with BTS pre-trained model. I am able to load pre-trained model but when I call inference_depther(), it runs into an error as "KeyError: 'cam_intrinsic'". Are there any default parameters that can be used?

![image](https://user-images.githubusercontent.com/25252447/174854795-890595b0-63da-4fbd-a4b6-1e6cf831317b.png)

P.S: I was able to run load model and predict with DepthFormer method in a similar way.

**Comment by zhyever** [comment] 2022-06-22 01:56
This error raises up from [here](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/c591b9711321450387ffa7322ec1db9a340347c2/depth/models/decode_heads/bts_head.py#L171), indicating a missed key of `cam_intrinsic` in `img_metas`. This key can be generated easily from the dataloader pipeline like [KITTI example](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/c591b9711321450387ffa7322ec1db9a340347c2/depth/datasets/pipelines/loading.py#L10) or pre-definition like [NYU example](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/c591b9711321450387ffa7322ec1db9a340347c2/depth/datasets/nyu.py#L144).

Moreover, remember to add this `cam_intrinsic` into the `meta_keys` of `Collect` as [example](https://github.com/zhyever/Monocular-Depth-Estimation-Toolbox/blob/c591b9711321450387ffa7322ec1db9a340347c2/configs/_base_/datasets/kitti.py#L18), so that the dataloader can collect the information to format the `img_metas` containing this key of `cam_intrinsic`.

**Comment by zhyever** [comment] 2022-06-22 13:10
As for BTS, I directly adopt the official codes provided by the authors. Hence, there may not be much difference to compare the inference time between our codebase and the official one.

As For DepthFormer, your provided inference time is in line with my perspective. It is slower than BTS mainly caused by the overhead introduced by the HAHI module.

By the way, I wonder if you apply our benchmark codes to measure the inference time. For a simple example, run `python ./tools/benchmark.py configs/xxx.py path/to/your/model/iter_xxx.pth`. You can see more accurate inference time results.

**Comment by zhyever** [comment] 2022-07-02 23:55
Close this issue for now.

**Closed by zhyever** 2022-07-02 23:55 UTC
